repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker

    -   id: check-executables-have-shebangs
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: destroyed-symlinks

    -   id: check-vcs-permalinks
    -   id: detect-private-key

    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
