name: ci

on:
  push:
    branches:
      - main

jobs:
    pre-commit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
        - uses: pre-commit/actions@v3.0.0

    validation:
        uses: ./.github/workflows/check.yml
        with:
          runner: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest, macos-11, macos-12, macos-13, macOS-latest]
